// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_CHARTTEMPHISTORY_H
#define _UI_COMP_CHARTTEMPHISTORY_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ChartTempHistory
#define UI_COMP_CHARTTEMPHISTORY_CHARTTEMPHISTORY 0
#define _UI_COMP_CHARTTEMPHISTORY_NUM 1
lv_obj_t * ui_ChartTempHistory_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
