// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT ChartTempHistory

lv_obj_t * ui_ChartTempHistory_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ChartTempHistory;
    cui_ChartTempHistory = lv_chart_create(comp_parent);
    lv_obj_set_width(cui_ChartTempHistory, 251);
    lv_obj_set_height(cui_ChartTempHistory, 72);
    lv_obj_set_x(cui_ChartTempHistory, 219);
    lv_obj_set_y(cui_ChartTempHistory, 45);
    lv_chart_set_type(cui_ChartTempHistory, LV_CHART_TYPE_LINE);
    lv_chart_set_range(cui_ChartTempHistory, LV_CHART_AXIS_PRIMARY_Y, 20, 60);
    lv_chart_set_axis_tick(cui_ChartTempHistory, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, false, 25);
    lv_chart_set_axis_tick(cui_ChartTempHistory, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 12);
    lv_chart_set_axis_tick(cui_ChartTempHistory, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * cui_ChartTempHistory_series_1 = lv_chart_add_series(cui_ChartTempHistory, lv_color_hex(0x1406B2),
                                                                            LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t cui_ChartTempHistory_series_1_array[] = { 20, 25, 30, 35, 40, 45, 50, 55 };
    lv_chart_set_ext_y_array(cui_ChartTempHistory, cui_ChartTempHistory_series_1, cui_ChartTempHistory_series_1_array);
    lv_obj_set_style_radius(cui_ChartTempHistory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(cui_ChartTempHistory, lv_color_hex(0x4040FF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(cui_ChartTempHistory, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(cui_ChartTempHistory, 5, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(cui_ChartTempHistory, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_ChartTempHistory, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_ChartTempHistory, &lv_font_montserrat_10, LV_PART_TICKS | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CHARTTEMPHISTORY_NUM);
    children[UI_COMP_CHARTTEMPHISTORY_CHARTTEMPHISTORY] = cui_ChartTempHistory;
    lv_obj_add_event_cb(cui_ChartTempHistory, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ChartTempHistory, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_ChartTempHistory_create_hook(cui_ChartTempHistory);
    return cui_ChartTempHistory;
}

