// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1MONITOR_H
#define UI_SCREEN1MONITOR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1Monitor
extern void ui_Screen1Monitor_screen_init(void);
extern void ui_Screen1Monitor_screen_destroy(void);
extern lv_obj_t * ui_Screen1Monitor;
extern lv_obj_t * ui_pane1header;
extern lv_obj_t * ui_LabelTitle;
extern lv_obj_t * ui_LabelDateTime;
extern lv_obj_t * ui_PanelTemperature;
extern lv_obj_t * ui_PanelGraph;
extern lv_obj_t * ui_PanelFluidNC;
extern lv_obj_t * ui_LabelMotorDrivers;
extern lv_obj_t * ui_LabelPeak;
extern lv_obj_t * ui_LabelX;
extern lv_obj_t * ui_LabelXTemp;
extern lv_obj_t * ui_LabelXTempPeak;
extern lv_obj_t * ui_LabelYL;
extern lv_obj_t * ui_LabelYLTemp;
extern lv_obj_t * ui_LabelYLTempPeak;
extern lv_obj_t * ui_LabelYR;
extern lv_obj_t * ui_LabelYRTemp;
extern lv_obj_t * ui_LabelYRTempPeak;
extern lv_obj_t * ui_LabelZ;
extern lv_obj_t * ui_LabelZTemp;
extern lv_obj_t * ui_LabelZTempPeak;
extern lv_obj_t * ui_LabelTempHistory;
extern lv_obj_t * ui_ChartTempHistory;
extern lv_obj_t * ui_LabelFanPercent;
extern lv_obj_t * ui_LabelPSU;
extern lv_obj_t * ui_LabelFluidNCStatus;
extern lv_obj_t * ui_LabelMCS;
extern lv_obj_t * ui_LabelWCS;
// CUSTOM VARIABLES
extern lv_obj_t * uic_label_title;
extern lv_obj_t * uic_label_datetime;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

