// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENMONITOR_H
#define UI_SCREENMONITOR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenMonitor
extern void ui_ScreenMonitor_screen_init(void);
extern void ui_ScreenMonitor_screen_destroy(void);
extern lv_obj_t * ui_ScreenMonitor;
extern lv_obj_t * ui_pane1header;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_label_title;
extern lv_obj_t * uic_label_datetime;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

