// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_label_datetime;
lv_obj_t * uic_label_title;
lv_obj_t * ui_ScreenMonitor = NULL;
lv_obj_t * ui_pane1header = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions

// build funtions

void ui_ScreenMonitor_screen_init(void)
{
    ui_ScreenMonitor = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMonitor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenMonitor, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMonitor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pane1header = lv_obj_create(ui_ScreenMonitor);
    lv_obj_set_width(ui_pane1header, 480);
    lv_obj_set_height(ui_pane1header, 25);
    lv_obj_set_align(ui_pane1header, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_pane1header, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pane1header, lv_color_hex(0x0707B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pane1header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_ScreenMonitor);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 12);
    lv_obj_set_y(ui_Label1, 5);
    lv_label_set_text(ui_Label1, "FluidDash");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_ScreenMonitor);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -10);
    lv_obj_set_y(ui_Label2, 5);
    lv_obj_set_align(ui_Label2, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label2, "DateTime");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_label_title = ui_Label1;
    uic_label_datetime = ui_Label2;

}

void ui_ScreenMonitor_screen_destroy(void)
{
    if(ui_ScreenMonitor) lv_obj_del(ui_ScreenMonitor);

    // NULL screen variables
    ui_ScreenMonitor = NULL;
    ui_pane1header = NULL;
    uic_label_title = NULL;
    ui_Label1 = NULL;
    uic_label_datetime = NULL;
    ui_Label2 = NULL;

}
