// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_label_datetime;
lv_obj_t * uic_label_title;
lv_obj_t * ui_Screen1Monitor = NULL;
lv_obj_t * ui_pane1header = NULL;
lv_obj_t * ui_LabelTitle = NULL;
lv_obj_t * ui_LabelDateTime = NULL;
lv_obj_t * ui_PanelTemperature = NULL;
lv_obj_t * ui_PanelGraph = NULL;
lv_obj_t * ui_PanelFluidNC = NULL;
lv_obj_t * ui_LabelMotorDrivers = NULL;
lv_obj_t * ui_LabelPeak = NULL;
lv_obj_t * ui_LabelX = NULL;
lv_obj_t * ui_LabelXTemp = NULL;
lv_obj_t * ui_LabelXTempPeak = NULL;
lv_obj_t * ui_LabelYL = NULL;
lv_obj_t * ui_LabelYLTemp = NULL;
lv_obj_t * ui_LabelYLTempPeak = NULL;
lv_obj_t * ui_LabelYR = NULL;
lv_obj_t * ui_LabelYRTemp = NULL;
lv_obj_t * ui_LabelYRTempPeak = NULL;
lv_obj_t * ui_LabelZ = NULL;
lv_obj_t * ui_LabelZTemp = NULL;
lv_obj_t * ui_LabelZTempPeak = NULL;
lv_obj_t * ui_LabelTempHistory = NULL;
lv_obj_t * ui_ChartTempHistory = NULL;
lv_obj_t * ui_LabelFanPercent = NULL;
lv_obj_t * ui_LabelPSU = NULL;
lv_obj_t * ui_LabelFluidNCStatus = NULL;
lv_obj_t * ui_LabelMCS = NULL;
lv_obj_t * ui_LabelWCS = NULL;
// event funtions

// build funtions

void ui_Screen1Monitor_screen_init(void)
{
    ui_Screen1Monitor = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1Monitor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1Monitor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1Monitor, lv_color_hex(0x0707B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1Monitor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pane1header = lv_obj_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_pane1header, 480);
    lv_obj_set_height(ui_pane1header, 25);
    lv_obj_set_align(ui_pane1header, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_pane1header, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pane1header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pane1header, lv_color_hex(0x0707B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pane1header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitle = lv_label_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_LabelTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTitle, 12);
    lv_obj_set_y(ui_LabelTitle, 5);
    lv_label_set_text(ui_LabelTitle, "FluidDash");
    lv_obj_set_style_text_color(ui_LabelTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDateTime = lv_label_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_LabelDateTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDateTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDateTime, -10);
    lv_obj_set_y(ui_LabelDateTime, 5);
    lv_obj_set_align(ui_LabelDateTime, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelDateTime, "");
    lv_obj_set_style_text_color(ui_LabelDateTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDateTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTemperature = lv_obj_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_PanelTemperature, 180);
    lv_obj_set_height(ui_PanelTemperature, 125);
    lv_obj_set_x(ui_PanelTemperature, 0);
    lv_obj_set_y(ui_PanelTemperature, 25);
    lv_obj_clear_flag(ui_PanelTemperature, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTemperature, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTemperature, lv_color_hex(0x0707B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTemperature, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTemperature, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelTemperature, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelGraph = lv_obj_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_PanelGraph, 300);
    lv_obj_set_height(ui_PanelGraph, 125);
    lv_obj_set_x(ui_PanelGraph, 180);
    lv_obj_set_y(ui_PanelGraph, 25);
    lv_obj_clear_flag(ui_PanelGraph, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelGraph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelGraph, lv_color_hex(0x0707B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelGraph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelFluidNC = lv_obj_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_PanelFluidNC, 480);
    lv_obj_set_height(ui_PanelFluidNC, 170);
    lv_obj_set_x(ui_PanelFluidNC, 0);
    lv_obj_set_y(ui_PanelFluidNC, 150);
    lv_obj_clear_flag(ui_PanelFluidNC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelFluidNC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelFluidNC, lv_color_hex(0x0707B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelFluidNC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMotorDrivers = lv_label_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_LabelMotorDrivers, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMotorDrivers, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMotorDrivers, 4);
    lv_obj_set_y(ui_LabelMotorDrivers, 29);
    lv_label_set_text(ui_LabelMotorDrivers, "Motor Drivers");
    lv_obj_set_style_text_color(ui_LabelMotorDrivers, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMotorDrivers, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelMotorDrivers, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelMotorDrivers, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMotorDrivers, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMotorDrivers, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelMotorDrivers, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelMotorDrivers, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelMotorDrivers, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelMotorDrivers, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelMotorDrivers, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPeak = lv_label_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_LabelPeak, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPeak, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPeak, 143);
    lv_obj_set_y(ui_LabelPeak, 29);
    lv_label_set_text(ui_LabelPeak, "Peak");
    lv_obj_set_style_text_color(ui_LabelPeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelPeak, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPeak, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelX = lv_label_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_LabelX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelX, 12);
    lv_obj_set_y(ui_LabelX, 44);
    lv_label_set_text(ui_LabelX, "X:");
    lv_obj_set_style_text_color(ui_LabelX, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelX, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelXTemp = lv_label_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_LabelXTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelXTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelXTemp, 33);
    lv_obj_set_y(ui_LabelXTemp, 44);
    lv_label_set_text(ui_LabelXTemp, "");
    lv_obj_set_style_text_color(ui_LabelXTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelXTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelXTempPeak = lv_label_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_LabelXTempPeak, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelXTempPeak, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelXTempPeak, 126);
    lv_obj_set_y(ui_LabelXTempPeak, 44);
    lv_label_set_text(ui_LabelXTempPeak, "");
    lv_obj_set_style_text_color(ui_LabelXTempPeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelXTempPeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelYL = lv_label_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_LabelYL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelYL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelYL, 5);
    lv_obj_set_y(ui_LabelYL, 61);
    lv_label_set_text(ui_LabelYL, "YL:");
    lv_obj_set_style_text_color(ui_LabelYL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelYL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelYL, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelYLTemp = lv_label_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_LabelYLTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelYLTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelYLTemp, 33);
    lv_obj_set_y(ui_LabelYLTemp, 61);
    lv_label_set_text(ui_LabelYLTemp, "");
    lv_obj_set_style_text_color(ui_LabelYLTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelYLTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelYLTemp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelYLTempPeak = lv_label_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_LabelYLTempPeak, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelYLTempPeak, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelYLTempPeak, 126);
    lv_obj_set_y(ui_LabelYLTempPeak, 61);
    lv_label_set_text(ui_LabelYLTempPeak, "");
    lv_obj_set_style_text_color(ui_LabelYLTempPeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelYLTempPeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelYLTempPeak, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelYR = lv_label_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_LabelYR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelYR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelYR, 4);
    lv_obj_set_y(ui_LabelYR, 80);
    lv_label_set_text(ui_LabelYR, "YR:");
    lv_obj_set_style_text_color(ui_LabelYR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelYR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelYR, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelYRTemp = lv_label_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_LabelYRTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelYRTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelYRTemp, 33);
    lv_obj_set_y(ui_LabelYRTemp, 80);
    lv_label_set_text(ui_LabelYRTemp, "");
    lv_obj_set_style_text_color(ui_LabelYRTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelYRTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelYRTemp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelYRTempPeak = lv_label_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_LabelYRTempPeak, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelYRTempPeak, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelYRTempPeak, 126);
    lv_obj_set_y(ui_LabelYRTempPeak, 80);
    lv_label_set_text(ui_LabelYRTempPeak, "");
    lv_obj_set_style_text_color(ui_LabelYRTempPeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelYRTempPeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelYRTempPeak, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelZ = lv_label_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_LabelZ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelZ, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelZ, 13);
    lv_obj_set_y(ui_LabelZ, 99);
    lv_label_set_text(ui_LabelZ, "Z:");
    lv_obj_set_style_text_color(ui_LabelZ, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelZ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelZ, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelZTemp = lv_label_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_LabelZTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelZTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelZTemp, 33);
    lv_obj_set_y(ui_LabelZTemp, 99);
    lv_label_set_text(ui_LabelZTemp, "");
    lv_obj_set_style_text_color(ui_LabelZTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelZTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelZTemp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelZTempPeak = lv_label_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_LabelZTempPeak, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelZTempPeak, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelZTempPeak, 126);
    lv_obj_set_y(ui_LabelZTempPeak, 99);
    lv_label_set_text(ui_LabelZTempPeak, "");
    lv_obj_set_style_text_color(ui_LabelZTempPeak, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelZTempPeak, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelZTempPeak, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTempHistory = lv_label_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_LabelTempHistory, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempHistory, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTempHistory, 187);
    lv_obj_set_y(ui_LabelTempHistory, 29);
    lv_label_set_text(ui_LabelTempHistory, "Temperature History");
    lv_obj_set_style_text_color(ui_LabelTempHistory, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempHistory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelTempHistory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelTempHistory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTempHistory, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempHistory, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelTempHistory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelTempHistory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelTempHistory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelTempHistory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelTempHistory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartTempHistory = ui_ChartTempHistory_create(ui_Screen1Monitor);
    lv_obj_set_x(ui_ChartTempHistory, 219);
    lv_obj_set_y(ui_ChartTempHistory, 45);

    ui_LabelFanPercent = lv_label_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_LabelFanPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFanPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFanPercent, 5);
    lv_obj_set_y(ui_LabelFanPercent, 129);
    lv_label_set_text(ui_LabelFanPercent, "Fan%:");
    lv_obj_set_style_text_color(ui_LabelFanPercent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFanPercent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPSU = lv_label_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_LabelPSU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPSU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPSU, 134);
    lv_obj_set_y(ui_LabelPSU, 129);
    lv_label_set_text(ui_LabelPSU, "PSU:");
    lv_obj_set_style_text_color(ui_LabelPSU, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPSU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelPSU, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFluidNCStatus = lv_label_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_LabelFluidNCStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFluidNCStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFluidNCStatus, 4);
    lv_obj_set_y(ui_LabelFluidNCStatus, 154);
    lv_label_set_text(ui_LabelFluidNCStatus, "FluidNC Status:");
    lv_obj_set_style_text_color(ui_LabelFluidNCStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFluidNCStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelFluidNCStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelFluidNCStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelFluidNCStatus, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFluidNCStatus, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelFluidNCStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelFluidNCStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelFluidNCStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelFluidNCStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelFluidNCStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMCS = lv_label_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_LabelMCS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMCS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMCS, 4);
    lv_obj_set_y(ui_LabelMCS, 300);
    lv_label_set_text(ui_LabelMCS, "MCS:");
    lv_obj_set_style_text_color(ui_LabelMCS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMCS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelMCS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelMCS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelMCS, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMCS, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelMCS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelMCS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelMCS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelMCS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelMCS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWCS = lv_label_create(ui_Screen1Monitor);
    lv_obj_set_width(ui_LabelWCS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWCS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWCS, 4);
    lv_obj_set_y(ui_LabelWCS, 265);
    lv_label_set_text(ui_LabelWCS, "WCS:");
    lv_obj_set_style_text_color(ui_LabelWCS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWCS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelWCS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelWCS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelWCS, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWCS, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelWCS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelWCS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelWCS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelWCS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelWCS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_label_title = ui_LabelTitle;
    uic_label_datetime = ui_LabelDateTime;

}

void ui_Screen1Monitor_screen_destroy(void)
{
    if(ui_Screen1Monitor) lv_obj_del(ui_Screen1Monitor);

    // NULL screen variables
    ui_Screen1Monitor = NULL;
    ui_pane1header = NULL;
    uic_label_title = NULL;
    ui_LabelTitle = NULL;
    uic_label_datetime = NULL;
    ui_LabelDateTime = NULL;
    ui_PanelTemperature = NULL;
    ui_PanelGraph = NULL;
    ui_PanelFluidNC = NULL;
    ui_LabelMotorDrivers = NULL;
    ui_LabelPeak = NULL;
    ui_LabelX = NULL;
    ui_LabelXTemp = NULL;
    ui_LabelXTempPeak = NULL;
    ui_LabelYL = NULL;
    ui_LabelYLTemp = NULL;
    ui_LabelYLTempPeak = NULL;
    ui_LabelYR = NULL;
    ui_LabelYRTemp = NULL;
    ui_LabelYRTempPeak = NULL;
    ui_LabelZ = NULL;
    ui_LabelZTemp = NULL;
    ui_LabelZTempPeak = NULL;
    ui_LabelTempHistory = NULL;
    ui_ChartTempHistory = NULL;
    ui_LabelFanPercent = NULL;
    ui_LabelPSU = NULL;
    ui_LabelFluidNCStatus = NULL;
    ui_LabelMCS = NULL;
    ui_LabelWCS = NULL;

}
